name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Csak akkor fut le, ha a "main" branch-be pusholsz

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        # Ha nincs szükséged csomagkezelésre, kihagyhatod

      - name: Build the project
        run: npm run build
        # Ha nincs build lépés, ezt is kihagyhatod

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Ez a mappa tartalmazza a kimeneti fájlokat, pl. index.html
